import uuid
from typing import Any, Protocol

from app.models.chat import ChatMessage, ChatRoom
from app.models.order import Order, OrderItem
from app.models.product import Product
from app.models.user import User


class UserServiceProtocol(Protocol):
    async def create(self, email: str, password: str, role: str = "buyer") -> User: ...

    async def get_sellers(self, limit: int, offset: int) -> tuple[list[User], int]: ...

    async def update(self, user_id: str, update_data: dict) -> User: ...

    async def delete(self, user_id: str) -> None: ...

    async def update_password(self, user: User, current_password: str, new_password: str) -> None: ...

    async def get_by_id(self, id: str | uuid.UUID) -> User: ...


class AuthServiceProtocol(Protocol):
    async def login(self, email: str, password: str) -> tuple[str, str]: ...

    async def refresh(self, token: str) -> tuple[str, str]: ...

    async def logout(self, token: str) -> None: ...


class ProductServiceProtocol(Protocol):
    async def create(
        self, seller_id: str, name: str, price: float, stock: int, description: str | None
    ) -> Product: ...

    async def update(self, product_id: str, update_data: dict) -> Product: ...

    async def delete(self, product_id: str) -> None: ...

    async def get_all(
        self, limit: int, offset: int, max_price: float | None = None, min_price: float | None = None
    ) -> tuple[list[Product], int]: ...

    async def get_by_id(self, product_id: str) -> Product: ...

    async def search(self, query: str | None, limit: int, offset: int) -> tuple[list[Product], int]: ...


class OrderServiceProtocol(Protocol):
    async def create_order(self, current_user: User, items: list[dict[str, Any]]) -> Order: ...

    async def complete_order(self, order_id: str) -> Order: ...

    async def get_by_id(self, order_id: str) -> Order: ...

    async def get_all_by_buyer(
        self, current_user: User, limit: int, offset: int
    ) -> tuple[list[Order], int]: ...

    async def get_seller_summary(self, seller_id: str) -> dict: ...

    async def cancel_order(self, order_id: str) -> Order: ...


class OrderItemServiceProtocol(Protocol):
    async def get_items(self, order_id: str, limit: int, offset: int) -> list[OrderItem]: ...


class ChatServiceProtocol(Protocol):
    async def create_room(self, seller_id: str, current_user: User) -> ChatRoom: ...

    async def get_room(self, room_id: str) -> ChatRoom: ...

    async def get_chat_history(self, room_id: str, limit: int, offset: int) -> list[ChatMessage]: ...

    async def save_message(
        self, room_id: str, text: str, current_user: User, attachment_url: str | None = None
    ) -> ChatMessage: ...


class MediaServiceProtocol(Protocol):
    async def generate_presigned_upload_post(self, object_name: str, file_type: str) -> dict: ...
    async def process_webhook_payload(self, payload: dict) -> None: ...
