from typing import Any, Protocol, TypeVar, runtime_checkable

from app.models.base import Base

Model = TypeVar("Model", bound=Base)


@runtime_checkable
class CRUDRepositoryProtocol(Protocol[Model]):
    async def create(self, data: Any) -> Model: ...

    async def update(self, instance: Model, update_data: dict[str, Any]) -> Model: ...

    async def delete(self, instance: Model) -> None: ...

    async def get_by_id(self, id: str) -> Model | None: ...

    async def get_all(self, limit: int, offset: int) -> tuple[list[Model], int]: ...

    async def commit(self) -> None: ...

    async def roll_back(self) -> None: ...


@runtime_checkable
class TokenRepositoryProtocol(Protocol):
    async def save_token(self, key: str, ttl_seconds: int, value: str = "active") -> None: ...

    async def get_token(self, key: str) -> str | None: ...

    async def delete_token(self, key: str) -> None: ...


@runtime_checkable
class MediaRepositoryProtocol(Protocol):
    async def get_active_urls(self) -> set[str]: ...

    async def update_product_media(self, product_id: str, new_url: str) -> None: ...

    async def update_user_avatar(self, user_id: str, new_url: str) -> None: ...

    async def update_chat_media(self, original_url: str, new_url: str) -> None: ...
