"""empty message

Revision ID: a7dfe3bc591b
Revises: e8810cc1106a
Create Date: 2026-06-30 08:48:52.948876

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7dfe3bc591b"
down_revision: str | Sequence[str] | None = "e8810cc1106a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    op.drop_table("chat_rooms")
    op.drop_table("chat_messages")
    op.drop_table("products")
    op.drop_table("order_items")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_items",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("order_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("product_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("quantity", sa.INTEGER(), nullable=False),
        sa.Column("price_at_purchase", sa.FLOAT(), nullable=False),
        sa.Column(
            "created_at", sa.DATETIME(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.CheckConstraint(
            "price_at_purchase > 0 AND price_at_purchase <= 9999999999999",
            name=op.f("check_price_at_purchase_range"),
        ),
        sa.CheckConstraint("quantity > 0 AND quantity <= 100000", name=op.f("check_quantity_range")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("seller_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("name", sa.VARCHAR(length=300), nullable=False),
        sa.Column("price", sa.FLOAT(), nullable=False),
        sa.Column("stock", sa.INTEGER(), nullable=False),
        sa.Column(
            "created_at", sa.DATETIME(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("image_url", sa.VARCHAR(length=500), nullable=True),
        sa.CheckConstraint("price > 0 AND price <= 9999999999999", name=op.f("check_price_range")),
        sa.CheckConstraint("stock >= 0 AND stock <= 1000000", name=op.f("check_stock_range")),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("room_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("sender_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("text", sa.TEXT(), nullable=False),
        sa.Column(
            "created_at", sa.DATETIME(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("attachment_url", sa.VARCHAR(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["chat_rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chat_rooms",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("buyer_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("seller_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DATETIME(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.CheckConstraint("buyer_id != seller_id", name=op.f("check_chat_room_different_users")),
        sa.ForeignKeyConstraint(
            ["buyer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("buyer_id", "seller_id", name=op.f("uq_chat_room_buyer_seller")),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("buyer_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("status", sa.VARCHAR(length=50), nullable=False),
        sa.Column(
            "created_at", sa.DATETIME(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["buyer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
