from collections.abc import AsyncIterator
from typing import Any, Protocol


class StorageClientProtocol(Protocol):
    async def download(self, object_key: str, dest_path: str) -> None: ...

    async def upload(self, object_key: str, src_path: str, content_type: str) -> None: ...

    async def delete(self, object_key: str) -> None: ...

    def list_objects(self) -> AsyncIterator[dict[str, Any]]: ...
